name: 🚀 Release + Publish

on:
  workflow_dispatch:
    inputs:
      versionChange:
        type: choice
        description: Select the version change
        required: true
        default: 'minor'
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION_CHANGE: ${{ github.event.inputs.versionChange }}

    permissions:
      contents: write
      id-token: write

    steps:
      - name: ✅ Use App Token for the Bot which is allowed to create releases
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.node-version'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: 📦 Install dependencies
        run: |
          npm ci

      - name: ↗ Update version
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global push.followTags true
          npm version ${{ env.VERSION_CHANGE }} -m "Release %s"

      - name: 🔍 Get meta data
        run: |
          VERSION=$(jq -r '.version' package.json)
          NAME=$(jq -r '.name' package.json)
          DISPLAY_NAME=$(jq -r '.displayName' package.json)

          echo VERSION=$VERSION >> $GITHUB_ENV
          echo NAME=$NAME >> $GITHUB_ENV
          echo DISPLAY_NAME=$DISPLAY_NAME >> $GITHUB_ENV

      - name: ⚒️ Build
        run: npm run build

      - name: 📌 Push tags
        run: git push

      - name: 🔆 Release ${{ env.VERSION }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: ${{ env.DISPLAY_NAME }} v${{ env.VERSION }}
          generate_release_notes: true

      - name: 📦 Publish to NPM Registry
        run: npm publish --provenance --access public
